version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
        container_name: elasticsearch
        restart: always
        volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
        hostname: elasticsearch
        ulimits:
         memlock:
           soft: -1
           hard: -1
        environment:
            - "discovery.type=single-node"
            - ELASTIC_PASSWORD=jG%PC50@$658
            - xpack.security.enabled=true
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.8
        container_name: kibana
        restart: always
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        depends_on:
          - elasticsearch
        environment:
         - SERVER_NAME=kibana
         - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
         - ELASTICSEARCH_USERNAME=elastic
         - ELASTICSEARCH_PASSWORD= jG%PC50@$658
        networks:
          - elknetwork
networks:
    elknetwork:
        driver: bridge
volumes:
  elasticsearch_data:
    driver: local
